name: Preview

# run when a pull request is made
on: [pull_request]

jobs:
  preview-setup:
    # Prevents action to be executed by forks and drafts
    if: github.event.action != 'closed' && github.event.pull_request.head.repo.full_name == github.repository
    uses: Qiskit/gh-actions/.github/workflows/code-engine-preview.yml@main
    with:
      code_engine_project: qiskit.org-preview
      docker_image_name: qiskit-org
      docker_image_port: "3000"
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}

  preview-cleanup:
    if: github.event.action == 'closed'
    uses: Qiskit/gh-actions/.github/workflows/code-engine-cleanup.yml@main
    with:
      code_engine_project: qiskit.org-preview
      docker_image_name: qiskit-org
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
