name: Preview

# run when a pull request is made
on: [pull_request]

jobs:
  code-engine:
    # Prevents action to be executed by forks and drafts
    if: github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.repository
    uses: Qiskit/gh-actions/.github/workflows/code-engine-preview.yml@last-configuration
    with:
      container_registry_namespace: community-digital
      code_engine_project: qiskit.org-preview
      code_engine_registry_secret: ibm-container-registry
      docker_image_name: qiskit-org
      docker_image_port: "3000"
      ibmcloud_region: us-south
      ibmcloud_resource_group: Quantum Community
    secrets:
      ibmcloud_account: ${{ secrets.IBMCLOUD_ACCOUNT }}
      ibmcloud_api_key: ${{ secrets.IBMCLOUD_API_KEY }}
