name: PR Preview Clean Up

# run when a pull request is closed
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      PR_TAG: pr-${{ github.event.pull_request.number }}
      DOCKER_IMAGE_NAME: qiskit-org

      IBMCLOUD_ACCOUNT: ${{ secrets.IBMCLOUD_ACCOUNT }}
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      IBMCLOUD_REGION: us-south
      IBMCLOUD_RESOURCE_GROUP: Quantum Community
      CODE_ENGINE_PROJECT: qiskit.org-preview

    steps:
      - name: Fetch content of the PR
        uses: actions/checkout@v2

      - name: Setup IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud --version
          ibmcloud config --check-version=false
          ibmcloud plugin install -f code-engine
          ibmcloud plugin install -f container-registry

      - name: Authenticate with IBM Cloud CLI
        run: |
          ibmcloud login -g "$IBMCLOUD_RESOURCE_GROUP" -r "$IBMCLOUD_REGION" -c "$IBMCLOUD_ACCOUNT" --apikey $IBMCLOUD_API_KEY

      # - name: Remove Docker image
      #   env:
      #     DOCKER_IMAGE_TAG: icr.io/community-digital/${{ env.DOCKER_IMAGE_NAME }}:${{ env.PR_TAG }}
      #   run: |
      #     ibmcloud cr image-rm "$DOCKER_IMAGE_TAG"

      - name: Remove Code Engine preview application
        env:
          APP_NAME: ${{ env.DOCKER_IMAGE_NAME }}-${{ env.PR_TAG }}
        run: |
          ibmcloud ce project select -n "$CODE_ENGINE_PROJECT"
          ibmcloud ce application delete \
            --name "$APP_NAME" \
            --wait \
            --ignore-not-found \
            --force
